version: '3'

tasks:
  # Генерация кода из .proto
  generate:
    desc: "Generate Go-code from proto files"
    aliases:
      - gen
    cmds:
      - protoc -I proto proto/**/*.proto --go_out=./gen/go/ --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative
